typography_spectrum: 0.13993
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.1684588
title: Round the World with Duygu
purpose: []
color:
  saturation: 0.1875
  brandStrength: 0.1702509
  rhythmicContrast: 0.75
  brandColors:
    - '#f3e1d7'
    - '#1b52c9'
    - '#190d17'
    - '#63abba'
    - '#d40b2b'
  lightness: 0.8064516
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Duygu Iseri
