name: Duygu Iseri
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25885
title: Round the World with Duygu
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3e1d7'
    - '#1b52c9'
    - '#190d17'
    - '#63abba'
    - '#d40b2b'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
